import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Test Assignment | Nazarii Vovk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  transactions,
}: Readonly<{
  children: React.ReactNode;
  transactions: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-neutral-50 font-sans">
          <main className="px-2 py-8 space-y-4 md:px-12">
            <h1 className="font-bold text-2xl">Test Assignment</h1>
            {children}
            {transactions}
          </main>
        </div>
      </body>
    </html>
  );
}
